// Code generated by goctl. DO NOT EDIT.
package types

type User struct {
	Username string `json:"username"`
}

type PostUserReq struct {
	Username string `form:"username"`
}

type PostUserResp struct {
	PostResp string `json:"post_resp"`
}
